In [27]:
import numpy as np

In [28]:
a = (1,2,3)
b = (4,5,6)
a + b

(1, 2, 3, 4, 5, 6)

In [29]:
a = np.array(a)
b = np.array(b)
a + b

array([5, 7, 9])

In [31]:
a - 2

array([-1,  0,  1])

In [32]:
a**3

array([ 1,  8, 27], dtype=int32)

In [33]:
a**b # elementwise

array([  1,  32, 729])

In [34]:
a*b

array([ 4, 10, 18])

In [35]:
a

array([1, 2, 3])

In [36]:
b

array([4, 5, 6])

In [37]:
np.matmul(a,b)

32

In [38]:
a

array([1, 2, 3])

In [39]:
b

array([4, 5, 6])

In [40]:
np.outer(a,b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [41]:
np.outer(b,a)

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [42]:
a

array([1, 2, 3])

In [43]:
c = np.array((0,3))

In [44]:
a + c # error, incompatible sizes

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [45]:
d = np.array((7))

In [46]:
a + d # even if sizes are not the same, numpy performs broadcasting when one of the elements is of size 1

array([ 8,  9, 10])

In [47]:
print(a.size,d.size)

3 1


In [ ]:
# convert a list into a numpy array

In [48]:
A = [4,5,2,7]
np.array(A)

array([4, 5, 2, 7])

In [ ]:
# Arrays of more than one dimension

In [49]:
e = np.array(((1,2),(3,4)))
e

array([[1, 2],
       [3, 4]])

In [50]:
f = np.array((-10,10))
f

array([-10,  10])

In [51]:
e + f # broadcasting

array([[-9, 12],
       [-7, 14]])

In [52]:
f = np.array(((-10,-10),(100,100)))
f

array([[-10, -10],
       [100, 100]])

In [53]:
e + f

array([[ -9,  -8],
       [103, 104]])

In [54]:
e = np.array((0,10,20,30))
e

array([ 0, 10, 20, 30])

In [59]:
f = np.array((1,2,3))
f

array([1, 2, 3])

In [62]:
e

array([ 0, 10, 20, 30])

In [60]:
e.reshape(4,1)

array([[ 0],
       [10],
       [20],
       [30]])

In [61]:
e.reshape(4,1) + f

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

[[1 2]
 [3 4]]


In [ ]:
# SUBSETS

In [63]:
r = np.array((3,3,6,1,-2,8.3,7.34,9))
r

array([ 3.  ,  3.  ,  6.  ,  1.  , -2.  ,  8.3 ,  7.34,  9.  ])

In [64]:
r[0]

3.0

In [65]:
r[-1] # last value

9.0

In [66]:
r[:3] # from 0th to 3rd (not included)

array([3., 3., 6.])

In [67]:
r[1:5:2]

array([3., 1.])

In [68]:
r[::2]

array([ 3.  ,  6.  , -2.  ,  7.34])

In [69]:
r[::-1] # reverse

array([ 9.  ,  7.34,  8.3 , -2.  ,  1.  ,  6.  ,  3.  ,  3.  ])

### Repeating values

In [70]:
np.zeros(10) # all zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
np.zeros((10,3)) # 10 rows, 3 cols

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.ones(3) # all ones

array([1., 1., 1.])

In [73]:
3*np.ones(4)

array([3., 3., 3., 3.])

In [74]:
np.pi

3.141592653589793

In [75]:
np.e

2.718281828459045

In [76]:
np.pi*np.ones(5)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

### RANDOM NUMBERS

In [77]:
np.random.random() # uniform distribution (0,1)

0.37699741526020647

In [78]:
np.random.random(3) # of size 3

array([0.92307802, 0.75112365, 0.94961167])

In [79]:
np.random.random((4,5)) 

array([[0.24867427, 0.44718897, 0.70048534, 0.49621647, 0.61534804],
       [0.46837745, 0.43993006, 0.63928976, 0.27654822, 0.88162161],
       [0.63697665, 0.67285524, 0.44886021, 0.33305236, 0.86140291],
       [0.26572171, 0.62747595, 0.84330323, 0.98982641, 0.01077814]])

In [80]:
np.random.seed(33) 
# fix "seed" for reproducibility

In [81]:
np.random.random(3)

array([0.24851013, 0.44997542, 0.4109408 ])

In [82]:
np.random.normal() # random.normal(loc=0.0, scale=1.0, size=None)
# gaussian distribution with mean = 0 (default) and sd =  1 (por default)

0.5939528918035563

In [85]:
np.random.normal(size = 3)

array([-0.01548176, -0.73092457, -0.18532259])

In [86]:
np.random.normal(size = (3,2))

array([[-1.01410294, -0.44799025],
       [-2.53889235, -0.15218195],
       [ 1.73950856, -0.38360253]])

In [89]:
np.random.normal(loc = 1.1, scale = 2.2, size = 3) # mean 1.1, sd 2.2, size 3

array([ 1.3944703 , -0.21431088,  1.348505  ])

### RANGES

In [90]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [91]:
np.arange(1, 11, 1) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
np.arange(1, 11, -1) 

array([], dtype=int32)

In [93]:
np.arange(10, 0, -1) 

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [94]:
np.arange(12) # from 0 (implicit), to 12 (not included), in steps of 1 (implicit)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
np.linspace(0, 3, 5) # del 0 al 3 (INCLUDED), returning an array of length 5

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

### RESHAPE

In [99]:
np.arange(12).reshape(4,3)  # convert it to a matrix of 4 rows and 3 cols

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
np.arange(11).reshape(4,3)  # error, non-commensurable

ValueError: cannot reshape array of size 11 into shape (4,3)

In [101]:
np.array(((1,2),(3,4)))

array([[1, 2],
       [3, 4]])

In [102]:
np.array(((1,2),(3,4))).reshape(4)

array([1, 2, 3, 4])

###

In [103]:
print(np.sin(0),np.cos(0))

0.0 1.0


In [104]:
np.sqrt(9)

3.0

### AXES

In [105]:
a = np.array(((1,2),(3,4)))
a

array([[1, 2],
       [3, 4]])

In [106]:
np.sum(a)

10

In [108]:
np.sum(a,axis=0)

array([4, 6])

In [109]:
np.sum(a,axis=1)

array([3, 7])

In [110]:
a1 = np.ones((3,2))
a1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [111]:
b1 = np.zeros((3,2))
b1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [112]:
np.concatenate([a1,b1])  # by default, axis = 0

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [113]:
np.concatenate([a1,b1], axis = 1)

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

### REPETITIONS

In [114]:
np.repeat(3,5) # repeat number 3 5 times

array([3, 3, 3, 3, 3])

In [115]:
np.repeat((1,2), 3) # repeat 1 3 times, then 2 3 times

array([1, 1, 1, 2, 2, 2])

In [116]:
np.repeat(np.arange(0,4), 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

### LOGIC

In [117]:
a = np.array((1,2,3))

In [118]:
a == 1

array([ True, False, False])

In [119]:
all(a == 1)

False

In [120]:
any(a == 1)

True

In [124]:
a

array([1, 2, 3])

In [123]:
a == 1

array([ True, False, False])

In [122]:
a == 2

array([False,  True, False])

In [74]:
np.logical_or(a == 1, a == 2)

array([ True,  True, False])

In [75]:
np.logical_and(a > 1, a < 4)

array([False,  True,  True])

In [125]:
np.logical_not(a > 1)

array([ True, False, False])

In [126]:
np.logical_xor(a > 1, a < 4)

array([ True, False, False])

### NA

In [78]:
np.nan

nan

In [127]:
q = np.array((1,2,np.nan,np.pi,np.sqrt(8)))
q

array([1.        , 2.        ,        nan, 3.14159265, 2.82842712])

In [128]:
np.isnan(q)

array([False, False,  True, False, False])

In [81]:
### SEARCH FOR ELEMENTS

In [129]:
a

array([1, 2, 3])

In [130]:
np.max(a)

3

In [131]:
np.argmax(a) # index of the element which is the maximum

2

In [132]:
a[np.argmax(a)]

3

In [133]:
q

array([1.        , 2.        ,        nan, 3.14159265, 2.82842712])

In [134]:
np.argmax(q)

2

In [135]:
q[np.argmax(q)]

nan

In [136]:
np.nanargmax(q) # ignore NA

3

In [141]:
q

array([1.        , 2.        ,        nan, 3.14159265, 2.82842712])

In [142]:
np.nanargmax(q)

3

In [143]:
q[3]

3.141592653589793

In [144]:
q[np.nanargmax(q)]

3.141592653589793

In [138]:
q

array([1.        , 2.        ,        nan, 3.14159265, 2.82842712])

In [139]:
q > 2

array([False, False, False,  True,  True])

In [140]:
np.where(q > 2) # search for where the condition is satisfied

(array([3, 4], dtype=int64),)

In [145]:
q[np.where(q > 2)]

array([3.14159265, 2.82842712])

In [147]:
q > 2

array([False, False, False,  True,  True])

In [148]:
np.where(q > 2, 999, 0) # where condition is met, replace with 999, where it is not, replace with 0

array([  0,   0,   0, 999, 999])

In [149]:
b = np.array((3,5,1,2,7,22,4,-23))
b

array([  3,   5,   1,   2,   7,  22,   4, -23])

In [150]:
np.sort(b)

array([-23,   1,   2,   3,   4,   5,   7,  22])

In [151]:
np.sort(b)[::-1]

array([ 22,   7,   5,   4,   3,   2,   1, -23])

In [98]:
b

array([  3,   5,   1,   2,   7,  22,   4, -23])